---
Name: locationkeeperroutes
After: framework/routes#coreroutes
---
Director:
  rules:
    'search//$Action/$ID' : 'Page_Controller',
    'pagefunction//$Action/$ID'  : 'Page_Controller'
    'codeHolderFunction//$Action/$ID'  : 'CodeHolder_Controller'