<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 14/10/16
 * Time: 10:04 AM
 */
class Note extends DataObject
{
    /**
     * Database Fields
     */
    private static $db = array(
        'Title' => 'Text',
        'NoteBody' => 'HTMLText'
    );

    private static $has_one = array(
        'ProjectPage' => 'ProjectPage'
    );

    private static $summary_fields = array(
        'Title' => 'Title',
        'BodySummary' => 'Summary',
    );

    public function BodySummary()
    {
        $big = $this->NoteBody;
        return $small = substr($big, 0, 200);
    }

    public function getCMSFields()
    {
        $fields = parent::getCMSFields();
        return $fields; // TODO: Change the autogenerated stub
    }


}
