<?php

class Server extends DataObject
{
    /**
     * Database Fields
     */
    private static $db = array(
        'CWPCheck' => 'Boolean',
        'ServerName' => 'Text',
        'ServerAddress' => 'Varchar(60)',
        'DevSSHUser' => 'Text',
        'DevSSHPass' => 'Text',
        'RootSSHUser' => 'Text',
        'RootSSHPass' => 'Text',
        'MySqlUser' => 'Text',
        'MySqlPass' => 'Text',
        'NameAddress' => 'Text'
    );

    /**
     * @return $ServerName + $ServerAddress
     */
    public function ServerFullName()
    {
        $fullName = $this->ServerName . ' | ' . $this->ServerAddress;
        return $fullName;
    }

    public function isCWPEnvironment()
    {
        $cwpEnvironment = '';
        if(isset($this->CWPCheck)){
            if($this->CWPCheck == 1)
            {
                $cwpEnvironment = 'YES';
            } elseif ($this->CWPCheck == 0){
                $cwpEnvironment = 'NO';
            }
        }
        return $cwpEnvironment;
    }

    public function TServerID()
    {
        $name = DataObject::get_by_id('Server', $this->ID);
        $n = $name->ServerName;
        return $n;
    }

    private static $summary_fields = array(
        'ServerName' => 'ServerName',
        'ServerAddress' => 'ServerAddress',
        'DevSSHUser' => 'DevSSHUser',
        'DevSSHPass' => 'DevSSHPass'
    );

    public function getCMSFields()
    {
        $fields = parent::getCMSFields();
        $fields->addFieldToTab('Root.Main', ReadonlyField::create('NameAddress', 'Server Name + Address'));
        return $fields; // TODO: Change the autogenerated stub
    }


    public function onBeforeWrite() {
        // check on first write action, aka "database row creation" (ID-property is not set)

        if(!$this->isInDb()) {
            $this->NameAddress = $this->ServerFullName(); // write $NameAddress to DB
        } else {
            $this->NameAddress = $this->ServerFullName(); // write $NameAddress to DB
        }

        parent::onBeforeWrite();
    }
}