<?php

class Server extends DataObject
{
    /**
     * Database Fields
     */
    private static $db = array(
        'ServerName' => 'Text',
        'ServerAddress' => 'Varchar(20)',
        'DevSSHUser' => 'Text',
        'DevSSHPass' => 'Text',
        'RootSSHUser' => 'Text',
        'RootSSHPass' => 'Text',
        'MySqlUser' => 'Text',
        'MySqlPass' => 'Text'
    );

    private static $summary_fields = array(
        'ServerName' => 'ServerName',
        'ServerAddress' => 'ServerAddress',
        'DevSSHUser' => 'DevSSHUser',
        'DevSSHPass' => 'DevSSHPass'
    );

    public function getCMSFields()
    {
        return parent::getCMSFields(); // TODO: Change the autogenerated stub
    }
}